/* Generated by scripts/optimize-images.py. Do not hand-edit. */
(function () {
  "use strict";

  var META = {
  "assets/gallery/gallery-01.jpeg": {
    "bytes": 152488,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 7240,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-240.webp",
        "width": 240
      },
      {
        "bytes": 12872,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-360.webp",
        "width": 360
      },
      {
        "bytes": 19654,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-480.webp",
        "width": 480
      },
      {
        "bytes": 37968,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-768.webp",
        "width": 768
      },
      {
        "bytes": 60430,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-1086.webp",
        "width": 1086
      },
      {
        "bytes": 85200,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-02.jpeg": {
    "bytes": 153266,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 9978,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-240.webp",
        "width": 240
      },
      {
        "bytes": 19692,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-360.webp",
        "width": 360
      },
      {
        "bytes": 30822,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-480.webp",
        "width": 480
      },
      {
        "bytes": 61964,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-768.webp",
        "width": 768
      },
      {
        "bytes": 102908,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-1086.webp",
        "width": 1086
      },
      {
        "bytes": 146370,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-03.jpeg": {
    "bytes": 153573,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 9176,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-240.webp",
        "width": 240
      },
      {
        "bytes": 16632,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-360.webp",
        "width": 360
      },
      {
        "bytes": 25208,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-480.webp",
        "width": 480
      },
      {
        "bytes": 49306,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-768.webp",
        "width": 768
      },
      {
        "bytes": 81362,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-1086.webp",
        "width": 1086
      },
      {
        "bytes": 119948,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-04.jpeg": {
    "bytes": 153513,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8698,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-240.webp",
        "width": 240
      },
      {
        "bytes": 16048,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-360.webp",
        "width": 360
      },
      {
        "bytes": 24260,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-480.webp",
        "width": 480
      },
      {
        "bytes": 47082,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-768.webp",
        "width": 768
      },
      {
        "bytes": 76628,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-1086.webp",
        "width": 1086
      },
      {
        "bytes": 112378,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-05.jpeg": {
    "bytes": 153458,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8546,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-240.webp",
        "width": 240
      },
      {
        "bytes": 15750,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-360.webp",
        "width": 360
      },
      {
        "bytes": 23674,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-480.webp",
        "width": 480
      },
      {
        "bytes": 47072,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-768.webp",
        "width": 768
      },
      {
        "bytes": 78856,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-1086.webp",
        "width": 1086
      },
      {
        "bytes": 117084,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-06.jpeg": {
    "bytes": 153270,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 7892,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-240.webp",
        "width": 240
      },
      {
        "bytes": 14138,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-360.webp",
        "width": 360
      },
      {
        "bytes": 21760,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-480.webp",
        "width": 480
      },
      {
        "bytes": 42984,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-768.webp",
        "width": 768
      },
      {
        "bytes": 69894,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-1086.webp",
        "width": 1086
      },
      {
        "bytes": 103162,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-07.jpeg": {
    "bytes": 153530,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8444,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-240.webp",
        "width": 240
      },
      {
        "bytes": 14918,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-360.webp",
        "width": 360
      },
      {
        "bytes": 22532,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-480.webp",
        "width": 480
      },
      {
        "bytes": 43348,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-768.webp",
        "width": 768
      },
      {
        "bytes": 70652,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-1086.webp",
        "width": 1086
      },
      {
        "bytes": 103678,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-08.jpeg": {
    "bytes": 137883,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 5690,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-240.webp",
        "width": 240
      },
      {
        "bytes": 9940,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-360.webp",
        "width": 360
      },
      {
        "bytes": 14822,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-480.webp",
        "width": 480
      },
      {
        "bytes": 27658,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-768.webp",
        "width": 768
      },
      {
        "bytes": 43836,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-1086.webp",
        "width": 1086
      },
      {
        "bytes": 64816,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-09.jpeg": {
    "bytes": 153178,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10150,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-240.webp",
        "width": 240
      },
      {
        "bytes": 18478,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-360.webp",
        "width": 360
      },
      {
        "bytes": 27924,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-480.webp",
        "width": 480
      },
      {
        "bytes": 54096,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-768.webp",
        "width": 768
      },
      {
        "bytes": 85816,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-10.jpeg": {
    "bytes": 153493,
    "height": 1024,
    "quality": null,
    "webp": [
      {
        "bytes": 8990,
        "height": 160,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-240.webp",
        "width": 240
      },
      {
        "bytes": 16964,
        "height": 240,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-360.webp",
        "width": 360
      },
      {
        "bytes": 26158,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-480.webp",
        "width": 480
      },
      {
        "bytes": 54800,
        "height": 512,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-768.webp",
        "width": 768
      },
      {
        "bytes": 91218,
        "height": 724,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-1086.webp",
        "width": 1086
      },
      {
        "bytes": 136224,
        "height": 965,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-1448.webp",
        "width": 1448
      },
      {
        "bytes": 146534,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-1536.webp",
        "width": 1536
      }
    ],
    "width": 1536
  },
  "assets/gallery/gallery-11.jpeg": {
    "bytes": 152881,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8052,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-240.webp",
        "width": 240
      },
      {
        "bytes": 13944,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-360.webp",
        "width": 360
      },
      {
        "bytes": 20696,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-480.webp",
        "width": 480
      },
      {
        "bytes": 40284,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-768.webp",
        "width": 768
      },
      {
        "bytes": 65096,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-1086.webp",
        "width": 1086
      },
      {
        "bytes": 94812,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-12.jpeg": {
    "bytes": 153443,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8516,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-240.webp",
        "width": 240
      },
      {
        "bytes": 15390,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-360.webp",
        "width": 360
      },
      {
        "bytes": 23442,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-480.webp",
        "width": 480
      },
      {
        "bytes": 46352,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-768.webp",
        "width": 768
      },
      {
        "bytes": 75974,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-1086.webp",
        "width": 1086
      },
      {
        "bytes": 109022,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-13.jpeg": {
    "bytes": 153322,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 7292,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-240.webp",
        "width": 240
      },
      {
        "bytes": 12920,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-360.webp",
        "width": 360
      },
      {
        "bytes": 19064,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-480.webp",
        "width": 480
      },
      {
        "bytes": 35298,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-768.webp",
        "width": 768
      },
      {
        "bytes": 54736,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-1086.webp",
        "width": 1086
      },
      {
        "bytes": 77950,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-14.jpeg": {
    "bytes": 153500,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 12682,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-240.webp",
        "width": 240
      },
      {
        "bytes": 22568,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-360.webp",
        "width": 360
      },
      {
        "bytes": 33650,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-480.webp",
        "width": 480
      },
      {
        "bytes": 62004,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-768.webp",
        "width": 768
      },
      {
        "bytes": 96596,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-15.jpeg": {
    "bytes": 134571,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 5090,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-240.webp",
        "width": 240
      },
      {
        "bytes": 8538,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-360.webp",
        "width": 360
      },
      {
        "bytes": 12650,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-480.webp",
        "width": 480
      },
      {
        "bytes": 24240,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-768.webp",
        "width": 768
      },
      {
        "bytes": 39648,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-1086.webp",
        "width": 1086
      },
      {
        "bytes": 59212,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-16.jpeg": {
    "bytes": 152477,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 6958,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-240.webp",
        "width": 240
      },
      {
        "bytes": 12000,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-360.webp",
        "width": 360
      },
      {
        "bytes": 17998,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-480.webp",
        "width": 480
      },
      {
        "bytes": 33996,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-768.webp",
        "width": 768
      },
      {
        "bytes": 55038,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-1086.webp",
        "width": 1086
      },
      {
        "bytes": 80180,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-17.jpeg": {
    "bytes": 153432,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 7638,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-240.webp",
        "width": 240
      },
      {
        "bytes": 13324,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-360.webp",
        "width": 360
      },
      {
        "bytes": 19810,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-480.webp",
        "width": 480
      },
      {
        "bytes": 37708,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-768.webp",
        "width": 768
      },
      {
        "bytes": 60546,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-1086.webp",
        "width": 1086
      },
      {
        "bytes": 86504,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-18.jpeg": {
    "bytes": 153461,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8928,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-240.webp",
        "width": 240
      },
      {
        "bytes": 16246,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-360.webp",
        "width": 360
      },
      {
        "bytes": 24632,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-480.webp",
        "width": 480
      },
      {
        "bytes": 48004,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-768.webp",
        "width": 768
      },
      {
        "bytes": 79230,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-1086.webp",
        "width": 1086
      },
      {
        "bytes": 113060,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-19.jpeg": {
    "bytes": 153261,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10492,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-240.webp",
        "width": 240
      },
      {
        "bytes": 18870,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-360.webp",
        "width": 360
      },
      {
        "bytes": 28612,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-480.webp",
        "width": 480
      },
      {
        "bytes": 55044,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-768.webp",
        "width": 768
      },
      {
        "bytes": 88196,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-20.jpeg": {
    "bytes": 150707,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 6708,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-240.webp",
        "width": 240
      },
      {
        "bytes": 11632,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-360.webp",
        "width": 360
      },
      {
        "bytes": 17304,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-480.webp",
        "width": 480
      },
      {
        "bytes": 32350,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-768.webp",
        "width": 768
      },
      {
        "bytes": 50004,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-1086.webp",
        "width": 1086
      },
      {
        "bytes": 71986,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-21.jpeg": {
    "bytes": 153054,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 7698,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-240.webp",
        "width": 240
      },
      {
        "bytes": 14516,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-360.webp",
        "width": 360
      },
      {
        "bytes": 22760,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-480.webp",
        "width": 480
      },
      {
        "bytes": 49614,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-768.webp",
        "width": 768
      },
      {
        "bytes": 84216,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-22.jpeg": {
    "bytes": 152378,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 5728,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-240.webp",
        "width": 240
      },
      {
        "bytes": 9812,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-360.webp",
        "width": 360
      },
      {
        "bytes": 14406,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-480.webp",
        "width": 480
      },
      {
        "bytes": 29422,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-768.webp",
        "width": 768
      },
      {
        "bytes": 52104,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-1086.webp",
        "width": 1086
      },
      {
        "bytes": 81808,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-23.jpeg": {
    "bytes": 152854,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10518,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-240.webp",
        "width": 240
      },
      {
        "bytes": 19578,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-360.webp",
        "width": 360
      },
      {
        "bytes": 29938,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-480.webp",
        "width": 480
      },
      {
        "bytes": 60826,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-768.webp",
        "width": 768
      },
      {
        "bytes": 102634,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-24.jpeg": {
    "bytes": 152540,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 5190,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-240.webp",
        "width": 240
      },
      {
        "bytes": 9416,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-360.webp",
        "width": 360
      },
      {
        "bytes": 14258,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-480.webp",
        "width": 480
      },
      {
        "bytes": 32222,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-768.webp",
        "width": 768
      },
      {
        "bytes": 60034,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-1086.webp",
        "width": 1086
      },
      {
        "bytes": 90922,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-25.jpeg": {
    "bytes": 153499,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10626,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-240.webp",
        "width": 240
      },
      {
        "bytes": 20028,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-360.webp",
        "width": 360
      },
      {
        "bytes": 31036,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-480.webp",
        "width": 480
      },
      {
        "bytes": 63080,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-768.webp",
        "width": 768
      },
      {
        "bytes": 102678,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-26.jpeg": {
    "bytes": 153387,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 10016,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-240.webp",
        "width": 240
      },
      {
        "bytes": 18398,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-360.webp",
        "width": 360
      },
      {
        "bytes": 28770,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-480.webp",
        "width": 480
      },
      {
        "bytes": 59974,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-768.webp",
        "width": 768
      },
      {
        "bytes": 100094,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-1086.webp",
        "width": 1086
      },
      {
        "bytes": 150362,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-27.jpeg": {
    "bytes": 153343,
    "height": 1024,
    "quality": null,
    "webp": [
      {
        "bytes": 11966,
        "height": 160,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-240.webp",
        "width": 240
      },
      {
        "bytes": 22764,
        "height": 240,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-360.webp",
        "width": 360
      },
      {
        "bytes": 34840,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-480.webp",
        "width": 480
      },
      {
        "bytes": 72856,
        "height": 512,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-768.webp",
        "width": 768
      },
      {
        "bytes": 115928,
        "height": 724,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-1086.webp",
        "width": 1086
      },
      {
        "bytes": 150420,
        "height": 965,
        "quality": 60,
        "src": "assets/variants/gallery/gallery-27-1448.webp",
        "width": 1448
      },
      {
        "bytes": 149560,
        "height": 1024,
        "quality": 54,
        "src": "assets/variants/gallery/gallery-27-1536.webp",
        "width": 1536
      }
    ],
    "width": 1536
  },
  "assets/gallery/gallery-28.jpeg": {
    "bytes": 153530,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11330,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-240.webp",
        "width": 240
      },
      {
        "bytes": 22162,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-360.webp",
        "width": 360
      },
      {
        "bytes": 35438,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-480.webp",
        "width": 480
      },
      {
        "bytes": 74138,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-768.webp",
        "width": 768
      },
      {
        "bytes": 121200,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-29.jpeg": {
    "bytes": 144960,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 8700,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-240.webp",
        "width": 240
      },
      {
        "bytes": 15504,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-360.webp",
        "width": 360
      },
      {
        "bytes": 23190,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-480.webp",
        "width": 480
      },
      {
        "bytes": 44066,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-768.webp",
        "width": 768
      },
      {
        "bytes": 70446,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-30.jpeg": {
    "bytes": 152688,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 9892,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-240.webp",
        "width": 240
      },
      {
        "bytes": 17770,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-360.webp",
        "width": 360
      },
      {
        "bytes": 26280,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-480.webp",
        "width": 480
      },
      {
        "bytes": 50406,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-768.webp",
        "width": 768
      },
      {
        "bytes": 79516,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-31.jpeg": {
    "bytes": 141823,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 8508,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-240.webp",
        "width": 240
      },
      {
        "bytes": 15394,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-360.webp",
        "width": 360
      },
      {
        "bytes": 22800,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-480.webp",
        "width": 480
      },
      {
        "bytes": 42494,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-768.webp",
        "width": 768
      },
      {
        "bytes": 66160,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-32.jpeg": {
    "bytes": 153446,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 8680,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-240.webp",
        "width": 240
      },
      {
        "bytes": 16332,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-360.webp",
        "width": 360
      },
      {
        "bytes": 25626,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-480.webp",
        "width": 480
      },
      {
        "bytes": 52002,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-768.webp",
        "width": 768
      },
      {
        "bytes": 86088,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-33.jpeg": {
    "bytes": 153442,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11442,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-240.webp",
        "width": 240
      },
      {
        "bytes": 21456,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-360.webp",
        "width": 360
      },
      {
        "bytes": 32926,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-480.webp",
        "width": 480
      },
      {
        "bytes": 66978,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-768.webp",
        "width": 768
      },
      {
        "bytes": 107944,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-34.jpeg": {
    "bytes": 153113,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 9790,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-240.webp",
        "width": 240
      },
      {
        "bytes": 18882,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-360.webp",
        "width": 360
      },
      {
        "bytes": 29762,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-480.webp",
        "width": 480
      },
      {
        "bytes": 62118,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-768.webp",
        "width": 768
      },
      {
        "bytes": 100782,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-35.jpeg": {
    "bytes": 152801,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11036,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-240.webp",
        "width": 240
      },
      {
        "bytes": 20880,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-360.webp",
        "width": 360
      },
      {
        "bytes": 32552,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-480.webp",
        "width": 480
      },
      {
        "bytes": 66032,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-768.webp",
        "width": 768
      },
      {
        "bytes": 108002,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-36.jpeg": {
    "bytes": 153560,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8094,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-240.webp",
        "width": 240
      },
      {
        "bytes": 13970,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-360.webp",
        "width": 360
      },
      {
        "bytes": 21198,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-480.webp",
        "width": 480
      },
      {
        "bytes": 40922,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-768.webp",
        "width": 768
      },
      {
        "bytes": 65788,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-1086.webp",
        "width": 1086
      },
      {
        "bytes": 94306,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-37.jpeg": {
    "bytes": 153535,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 7938,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-240.webp",
        "width": 240
      },
      {
        "bytes": 15262,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-360.webp",
        "width": 360
      },
      {
        "bytes": 23612,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-480.webp",
        "width": 480
      },
      {
        "bytes": 49780,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-768.webp",
        "width": 768
      },
      {
        "bytes": 86692,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-1086.webp",
        "width": 1086
      },
      {
        "bytes": 130450,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-38.jpeg": {
    "bytes": 153181,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11944,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-240.webp",
        "width": 240
      },
      {
        "bytes": 22684,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-360.webp",
        "width": 360
      },
      {
        "bytes": 34746,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-480.webp",
        "width": 480
      },
      {
        "bytes": 67886,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-768.webp",
        "width": 768
      },
      {
        "bytes": 110848,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-39.jpeg": {
    "bytes": 152850,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8230,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-240.webp",
        "width": 240
      },
      {
        "bytes": 15348,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-360.webp",
        "width": 360
      },
      {
        "bytes": 24730,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-480.webp",
        "width": 480
      },
      {
        "bytes": 51640,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-768.webp",
        "width": 768
      },
      {
        "bytes": 89068,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-1086.webp",
        "width": 1086
      },
      {
        "bytes": 129952,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-40.jpeg": {
    "bytes": 153183,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 12226,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-240.webp",
        "width": 240
      },
      {
        "bytes": 22436,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-360.webp",
        "width": 360
      },
      {
        "bytes": 33776,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-480.webp",
        "width": 480
      },
      {
        "bytes": 63864,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-768.webp",
        "width": 768
      },
      {
        "bytes": 102840,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-41.jpeg": {
    "bytes": 153193,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10250,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-240.webp",
        "width": 240
      },
      {
        "bytes": 18696,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-360.webp",
        "width": 360
      },
      {
        "bytes": 28062,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-480.webp",
        "width": 480
      },
      {
        "bytes": 54256,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-768.webp",
        "width": 768
      },
      {
        "bytes": 86230,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-42.jpeg": {
    "bytes": 153158,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11358,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-240.webp",
        "width": 240
      },
      {
        "bytes": 21130,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-360.webp",
        "width": 360
      },
      {
        "bytes": 32490,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-480.webp",
        "width": 480
      },
      {
        "bytes": 63680,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-768.webp",
        "width": 768
      },
      {
        "bytes": 101480,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-43.jpeg": {
    "bytes": 153393,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11224,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-240.webp",
        "width": 240
      },
      {
        "bytes": 22310,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-360.webp",
        "width": 360
      },
      {
        "bytes": 36064,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-480.webp",
        "width": 480
      },
      {
        "bytes": 79778,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-768.webp",
        "width": 768
      },
      {
        "bytes": 135476,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-44.jpeg": {
    "bytes": 153513,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8756,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-240.webp",
        "width": 240
      },
      {
        "bytes": 16634,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-360.webp",
        "width": 360
      },
      {
        "bytes": 26292,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-480.webp",
        "width": 480
      },
      {
        "bytes": 54538,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-768.webp",
        "width": 768
      },
      {
        "bytes": 91602,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-1086.webp",
        "width": 1086
      },
      {
        "bytes": 132750,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-45.jpeg": {
    "bytes": 152359,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10184,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-240.webp",
        "width": 240
      },
      {
        "bytes": 19164,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-360.webp",
        "width": 360
      },
      {
        "bytes": 29490,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-480.webp",
        "width": 480
      },
      {
        "bytes": 56948,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-768.webp",
        "width": 768
      },
      {
        "bytes": 90342,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-46.jpeg": {
    "bytes": 152946,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 10754,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-240.webp",
        "width": 240
      },
      {
        "bytes": 20768,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-360.webp",
        "width": 360
      },
      {
        "bytes": 32326,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-480.webp",
        "width": 480
      },
      {
        "bytes": 67494,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-768.webp",
        "width": 768
      },
      {
        "bytes": 112106,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-47.jpeg": {
    "bytes": 153522,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11330,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-240.webp",
        "width": 240
      },
      {
        "bytes": 21948,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-360.webp",
        "width": 360
      },
      {
        "bytes": 34688,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-480.webp",
        "width": 480
      },
      {
        "bytes": 71526,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-768.webp",
        "width": 768
      },
      {
        "bytes": 117400,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-48.jpeg": {
    "bytes": 153270,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 9414,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-240.webp",
        "width": 240
      },
      {
        "bytes": 16654,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-360.webp",
        "width": 360
      },
      {
        "bytes": 24828,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-480.webp",
        "width": 480
      },
      {
        "bytes": 48802,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-768.webp",
        "width": 768
      },
      {
        "bytes": 79436,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-49.jpeg": {
    "bytes": 153527,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 11810,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-240.webp",
        "width": 240
      },
      {
        "bytes": 21640,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-360.webp",
        "width": 360
      },
      {
        "bytes": 32998,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-480.webp",
        "width": 480
      },
      {
        "bytes": 66322,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-768.webp",
        "width": 768
      },
      {
        "bytes": 108950,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-50.jpeg": {
    "bytes": 152669,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 9880,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-240.webp",
        "width": 240
      },
      {
        "bytes": 18690,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-360.webp",
        "width": 360
      },
      {
        "bytes": 29850,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-480.webp",
        "width": 480
      },
      {
        "bytes": 63782,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-768.webp",
        "width": 768
      },
      {
        "bytes": 105744,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-51.jpeg": {
    "bytes": 153534,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 6748,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-240.webp",
        "width": 240
      },
      {
        "bytes": 13194,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-360.webp",
        "width": 360
      },
      {
        "bytes": 20674,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-480.webp",
        "width": 480
      },
      {
        "bytes": 44336,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-768.webp",
        "width": 768
      },
      {
        "bytes": 75642,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-1086.webp",
        "width": 1086
      },
      {
        "bytes": 108310,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-52.jpeg": {
    "bytes": 153085,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 7698,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-240.webp",
        "width": 240
      },
      {
        "bytes": 13492,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-360.webp",
        "width": 360
      },
      {
        "bytes": 20012,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-480.webp",
        "width": 480
      },
      {
        "bytes": 39290,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-768.webp",
        "width": 768
      },
      {
        "bytes": 64634,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-1086.webp",
        "width": 1086
      },
      {
        "bytes": 98254,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-53.jpeg": {
    "bytes": 153579,
    "height": 1448,
    "quality": null,
    "webp": [
      {
        "bytes": 13900,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-240.webp",
        "width": 240
      },
      {
        "bytes": 25202,
        "height": 480,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-360.webp",
        "width": 360
      },
      {
        "bytes": 38182,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-480.webp",
        "width": 480
      },
      {
        "bytes": 74268,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-768.webp",
        "width": 768
      },
      {
        "bytes": 116346,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/menu/menu-1.jpeg": {
    "bytes": 153339,
    "height": 1103,
    "quality": null,
    "webp": [
      {
        "bytes": 45748,
        "height": 371,
        "quality": 72,
        "src": "assets/variants/menu/menu-1-480.webp",
        "width": 480
      },
      {
        "bytes": 75974,
        "height": 495,
        "quality": 72,
        "src": "assets/variants/menu/menu-1-640.webp",
        "width": 640
      },
      {
        "bytes": 145740,
        "height": 743,
        "quality": 66,
        "src": "assets/variants/menu/menu-1-960.webp",
        "width": 960
      }
    ],
    "width": 1426
  },
  "assets/menu/menu-2.jpeg": {
    "bytes": 153346,
    "height": 1103,
    "quality": null,
    "webp": [
      {
        "bytes": 44554,
        "height": 371,
        "quality": 72,
        "src": "assets/variants/menu/menu-2-480.webp",
        "width": 480
      },
      {
        "bytes": 73054,
        "height": 495,
        "quality": 72,
        "src": "assets/variants/menu/menu-2-640.webp",
        "width": 640
      },
      {
        "bytes": 142874,
        "height": 743,
        "quality": 72,
        "src": "assets/variants/menu/menu-2-960.webp",
        "width": 960
      }
    ],
    "width": 1426
  },
  "assets/restaurant/marjorie-gaboyau.jpeg": {
    "bytes": 110302,
    "height": 1537,
    "quality": null,
    "webp": [
      {
        "bytes": 6866,
        "height": 361,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-240.webp",
        "width": 240
      },
      {
        "bytes": 11194,
        "height": 541,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-360.webp",
        "width": 360
      },
      {
        "bytes": 16272,
        "height": 721,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-480.webp",
        "width": 480
      },
      {
        "bytes": 29820,
        "height": 1154,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-768.webp",
        "width": 768
      },
      {
        "bytes": 44980,
        "height": 1537,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-1023.webp",
        "width": 1023
      }
    ],
    "width": 1023
  },
  "assets/restaurant/oswald-gaboyau.jpeg": {
    "bytes": 117047,
    "height": 1537,
    "quality": null,
    "webp": [
      {
        "bytes": 6816,
        "height": 361,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-240.webp",
        "width": 240
      },
      {
        "bytes": 11408,
        "height": 541,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-360.webp",
        "width": 360
      },
      {
        "bytes": 16688,
        "height": 721,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-480.webp",
        "width": 480
      },
      {
        "bytes": 32720,
        "height": 1154,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-768.webp",
        "width": 768
      },
      {
        "bytes": 52178,
        "height": 1537,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-1023.webp",
        "width": 1023
      }
    ],
    "width": 1023
  },
  "assets/restaurant/seven-wonders-dining-room-art.jpeg": {
    "bytes": 153305,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 8256,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-240.webp",
        "width": 240
      },
      {
        "bytes": 15632,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-360.webp",
        "width": 360
      },
      {
        "bytes": 24752,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-480.webp",
        "width": 480
      },
      {
        "bytes": 52844,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-768.webp",
        "width": 768
      },
      {
        "bytes": 91430,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-1086.webp",
        "width": 1086
      },
      {
        "bytes": 133772,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/restaurant/seven-wonders-dining-room-front.jpeg": {
    "bytes": 153533,
    "height": 1086,
    "quality": null,
    "webp": [
      {
        "bytes": 10126,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-240.webp",
        "width": 240
      },
      {
        "bytes": 18940,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-360.webp",
        "width": 360
      },
      {
        "bytes": 29406,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-480.webp",
        "width": 480
      },
      {
        "bytes": 58796,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-768.webp",
        "width": 768
      },
      {
        "bytes": 97098,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-1086.webp",
        "width": 1086
      },
      {
        "bytes": 139520,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/restaurant/seven-wonders-exterior.jpeg": {
    "bytes": 153393,
    "height": 960,
    "quality": null,
    "webp": [
      {
        "bytes": 13282,
        "height": 180,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-exterior-240.webp",
        "width": 240
      },
      {
        "bytes": 26390,
        "height": 270,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-exterior-360.webp",
        "width": 360
      },
      {
        "bytes": 42102,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-exterior-480.webp",
        "width": 480
      },
      {
        "bytes": 89788,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-exterior-768.webp",
        "width": 768
      },
      {
        "bytes": 145864,
        "height": 814,
        "quality": 66,
        "src": "assets/variants/restaurant/seven-wonders-exterior-1086.webp",
        "width": 1086
      },
      {
        "bytes": 149122,
        "height": 960,
        "quality": 48,
        "src": "assets/variants/restaurant/seven-wonders-exterior-1280.webp",
        "width": 1280
      }
    ],
    "width": 1280
  }
};

  function esc(value) {
    return String(value == null ? "" : value)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/\"/g, "&quot;").replace(/'/g, "&#39;");
  }
  function meta(src) { return META[String(src || "").trim()] || null; }
  function attrs(src, opts) {
    opts = opts || {};
    var m = meta(src) || {};
    var out = { src: src, width: m.width || opts.width || 1, height: m.height || opts.height || 1,
      loading: opts.loading || "lazy", decoding: opts.decoding || "async" };
    var srcset = webpSrcset(src);
    if (srcset) { out.srcset = srcset; out.sizes = opts.sizes || "100vw"; }
    if (opts.fetchpriority) out.fetchpriority = opts.fetchpriority;
    return out;
  }
  function webpSrcset(src) {
    var m = meta(src);
    return m && m.webp && m.webp.length ? m.webp.map(function (v) { return v.src + " " + v.width + "w"; }).join(", ") : "";
  }
  function makeSource(src, sizes) {
    var srcset = webpSrcset(src);
    if (!srcset) return null;
    var s = document.createElement("source");
    s.type = "image/webp";
    s.srcset = srcset;
    s.sizes = sizes || "100vw";
    return s;
  }
  function applyToImage(img, src, alt, opts) {
    var a = attrs(src, opts);
    Object.keys(a).forEach(function (k) { img.setAttribute(k, a[k]); });
    img.alt = alt || "";
    var parent = img.parentNode;
    if (parent && parent.tagName === "PICTURE") {
      var source = parent.querySelector('source[type="image/webp"]');
      var fresh = makeSource(src, (opts || {}).sizes);
      if (fresh && source) { source.srcset = fresh.srcset; source.sizes = fresh.sizes; }
      else if (fresh) parent.insertBefore(fresh, img);
      else if (source) source.remove();
    }
  }
  function picture(src, alt, opts) {
    opts = opts || {};
    var p = document.createElement("picture");
    if (opts.className) p.className = opts.className;
    var source = makeSource(src, opts.sizes);
    if (source) p.appendChild(source);
    var img = document.createElement("img");
    if (opts.imgClass) img.className = opts.imgClass;
    applyToImage(img, src, alt, opts);
    p.appendChild(img);
    return p;
  }
  function html(src, alt, opts) {
    opts = opts || {};
    var m = meta(src) || {};
    var cls = opts.imgClass ? ' class="' + esc(opts.imgClass) + '"' : "";
    var source = webpSrcset(src)
      ? '<source type="image/webp" srcset="' + esc(webpSrcset(src)) + '" sizes="' + esc(opts.sizes || "100vw") + '">'
      : "";
    var fetch = opts.fetchpriority ? ' fetchpriority="' + esc(opts.fetchpriority) + '"' : "";
    return '<picture>' + source + '<img' + cls + ' src="' + esc(src) + '" alt="' + esc(alt || "") + '" width="' +
      esc(m.width || opts.width || 1) + '" height="' + esc(m.height || opts.height || 1) + '" loading="' +
      esc(opts.loading || "lazy") + '" decoding="async"' + fetch + '></picture>';
  }

  window.SW_IMAGE_META = META;
  window.SWImage = { meta: meta, attrs: attrs, picture: picture, html: html, applyToImage: applyToImage, webpSrcset: webpSrcset };
})();
