/* Generated by scripts/optimize-images.py. Do not hand-edit. */
(function () {
  "use strict";

  var META = {
  "assets/gallery/gallery-01.jpeg": {
    "bytes": 152488,
    "height": 1086,
    "quality": 75,
    "webp": [
      {
        "bytes": 19638,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-480.webp",
        "width": 480
      },
      {
        "bytes": 37952,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-768.webp",
        "width": 768
      },
      {
        "bytes": 60434,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-1086.webp",
        "width": 1086
      },
      {
        "bytes": 85106,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-01-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-02.jpeg": {
    "bytes": 153266,
    "height": 1086,
    "quality": 51,
    "webp": [
      {
        "bytes": 30802,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-480.webp",
        "width": 480
      },
      {
        "bytes": 61952,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-768.webp",
        "width": 768
      },
      {
        "bytes": 102898,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-1086.webp",
        "width": 1086
      },
      {
        "bytes": 146320,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-02-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-03.jpeg": {
    "bytes": 153573,
    "height": 1086,
    "quality": 62,
    "webp": [
      {
        "bytes": 25260,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-480.webp",
        "width": 480
      },
      {
        "bytes": 49308,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-768.webp",
        "width": 768
      },
      {
        "bytes": 81404,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-1086.webp",
        "width": 1086
      },
      {
        "bytes": 119870,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-03-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-04.jpeg": {
    "bytes": 153513,
    "height": 1086,
    "quality": 66,
    "webp": [
      {
        "bytes": 24260,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-480.webp",
        "width": 480
      },
      {
        "bytes": 47124,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-768.webp",
        "width": 768
      },
      {
        "bytes": 76586,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-1086.webp",
        "width": 1086
      },
      {
        "bytes": 112554,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-04-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-05.jpeg": {
    "bytes": 153458,
    "height": 1086,
    "quality": 63,
    "webp": [
      {
        "bytes": 23688,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-480.webp",
        "width": 480
      },
      {
        "bytes": 47168,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-768.webp",
        "width": 768
      },
      {
        "bytes": 78852,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-1086.webp",
        "width": 1086
      },
      {
        "bytes": 117092,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-05-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-06.jpeg": {
    "bytes": 153270,
    "height": 1086,
    "quality": 69,
    "webp": [
      {
        "bytes": 21742,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-480.webp",
        "width": 480
      },
      {
        "bytes": 42974,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-768.webp",
        "width": 768
      },
      {
        "bytes": 69910,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-1086.webp",
        "width": 1086
      },
      {
        "bytes": 103234,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-06-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-07.jpeg": {
    "bytes": 153530,
    "height": 1086,
    "quality": 70,
    "webp": [
      {
        "bytes": 22538,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-480.webp",
        "width": 480
      },
      {
        "bytes": 43344,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-768.webp",
        "width": 768
      },
      {
        "bytes": 70658,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-1086.webp",
        "width": 1086
      },
      {
        "bytes": 103598,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-07-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-08.jpeg": {
    "bytes": 137883,
    "height": 1086,
    "quality": 84,
    "webp": [
      {
        "bytes": 14828,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-480.webp",
        "width": 480
      },
      {
        "bytes": 27702,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-768.webp",
        "width": 768
      },
      {
        "bytes": 43938,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-1086.webp",
        "width": 1086
      },
      {
        "bytes": 64704,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-08-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-09.jpeg": {
    "bytes": 153178,
    "height": 1448,
    "quality": 76,
    "webp": [
      {
        "bytes": 27930,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-480.webp",
        "width": 480
      },
      {
        "bytes": 53984,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-768.webp",
        "width": 768
      },
      {
        "bytes": 85740,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-09-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-10.jpeg": {
    "bytes": 153493,
    "height": 1024,
    "quality": 52,
    "webp": [
      {
        "bytes": 26464,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-480.webp",
        "width": 480
      },
      {
        "bytes": 56274,
        "height": 512,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-768.webp",
        "width": 768
      },
      {
        "bytes": 92730,
        "height": 724,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-1086.webp",
        "width": 1086
      },
      {
        "bytes": 138578,
        "height": 965,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-1448.webp",
        "width": 1448
      },
      {
        "bytes": 148856,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-10-1536.webp",
        "width": 1536
      }
    ],
    "width": 1536
  },
  "assets/gallery/gallery-11.jpeg": {
    "bytes": 152881,
    "height": 1086,
    "quality": 75,
    "webp": [
      {
        "bytes": 20692,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-480.webp",
        "width": 480
      },
      {
        "bytes": 40096,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-768.webp",
        "width": 768
      },
      {
        "bytes": 65150,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-1086.webp",
        "width": 1086
      },
      {
        "bytes": 94754,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-11-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-12.jpeg": {
    "bytes": 153443,
    "height": 1086,
    "quality": 68,
    "webp": [
      {
        "bytes": 23394,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-480.webp",
        "width": 480
      },
      {
        "bytes": 46370,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-768.webp",
        "width": 768
      },
      {
        "bytes": 75942,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-1086.webp",
        "width": 1086
      },
      {
        "bytes": 108940,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-12-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-13.jpeg": {
    "bytes": 153322,
    "height": 1086,
    "quality": 81,
    "webp": [
      {
        "bytes": 19096,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-480.webp",
        "width": 480
      },
      {
        "bytes": 35250,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-768.webp",
        "width": 768
      },
      {
        "bytes": 54680,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-1086.webp",
        "width": 1086
      },
      {
        "bytes": 77832,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-13-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-14.jpeg": {
    "bytes": 153500,
    "height": 1448,
    "quality": 70,
    "webp": [
      {
        "bytes": 33662,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-480.webp",
        "width": 480
      },
      {
        "bytes": 62034,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-768.webp",
        "width": 768
      },
      {
        "bytes": 96506,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-14-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-15.jpeg": {
    "bytes": 134571,
    "height": 1086,
    "quality": 84,
    "webp": [
      {
        "bytes": 12654,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-480.webp",
        "width": 480
      },
      {
        "bytes": 24260,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-768.webp",
        "width": 768
      },
      {
        "bytes": 39646,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-1086.webp",
        "width": 1086
      },
      {
        "bytes": 59272,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-15-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-16.jpeg": {
    "bytes": 152477,
    "height": 1086,
    "quality": 79,
    "webp": [
      {
        "bytes": 18010,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-480.webp",
        "width": 480
      },
      {
        "bytes": 34032,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-768.webp",
        "width": 768
      },
      {
        "bytes": 55052,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-1086.webp",
        "width": 1086
      },
      {
        "bytes": 80214,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-16-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-17.jpeg": {
    "bytes": 153432,
    "height": 1086,
    "quality": 77,
    "webp": [
      {
        "bytes": 19792,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-480.webp",
        "width": 480
      },
      {
        "bytes": 37692,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-768.webp",
        "width": 768
      },
      {
        "bytes": 60620,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-1086.webp",
        "width": 1086
      },
      {
        "bytes": 86514,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-17-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-18.jpeg": {
    "bytes": 153461,
    "height": 1086,
    "quality": 65,
    "webp": [
      {
        "bytes": 24608,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-480.webp",
        "width": 480
      },
      {
        "bytes": 47958,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-768.webp",
        "width": 768
      },
      {
        "bytes": 79212,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-1086.webp",
        "width": 1086
      },
      {
        "bytes": 113058,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-18-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-19.jpeg": {
    "bytes": 153261,
    "height": 1448,
    "quality": 76,
    "webp": [
      {
        "bytes": 28552,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-480.webp",
        "width": 480
      },
      {
        "bytes": 54976,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-768.webp",
        "width": 768
      },
      {
        "bytes": 88406,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-19-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-20.jpeg": {
    "bytes": 150707,
    "height": 1086,
    "quality": 84,
    "webp": [
      {
        "bytes": 17242,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-480.webp",
        "width": 480
      },
      {
        "bytes": 32402,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-768.webp",
        "width": 768
      },
      {
        "bytes": 50052,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-1086.webp",
        "width": 1086
      },
      {
        "bytes": 71926,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-20-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-21.jpeg": {
    "bytes": 153054,
    "height": 1448,
    "quality": 79,
    "webp": [
      {
        "bytes": 22764,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-480.webp",
        "width": 480
      },
      {
        "bytes": 49628,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-768.webp",
        "width": 768
      },
      {
        "bytes": 84184,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-21-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-22.jpeg": {
    "bytes": 152378,
    "height": 1086,
    "quality": 79,
    "webp": [
      {
        "bytes": 14384,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-480.webp",
        "width": 480
      },
      {
        "bytes": 29422,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-768.webp",
        "width": 768
      },
      {
        "bytes": 52076,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-1086.webp",
        "width": 1086
      },
      {
        "bytes": 81860,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-22-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-23.jpeg": {
    "bytes": 152854,
    "height": 1448,
    "quality": 72,
    "webp": [
      {
        "bytes": 29964,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-480.webp",
        "width": 480
      },
      {
        "bytes": 60830,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-768.webp",
        "width": 768
      },
      {
        "bytes": 102602,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-23-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-24.jpeg": {
    "bytes": 152540,
    "height": 1086,
    "quality": 77,
    "webp": [
      {
        "bytes": 14242,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-480.webp",
        "width": 480
      },
      {
        "bytes": 32254,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-768.webp",
        "width": 768
      },
      {
        "bytes": 60030,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-1086.webp",
        "width": 1086
      },
      {
        "bytes": 90908,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-24-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-25.jpeg": {
    "bytes": 153499,
    "height": 1448,
    "quality": 72,
    "webp": [
      {
        "bytes": 31052,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-480.webp",
        "width": 480
      },
      {
        "bytes": 62996,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-768.webp",
        "width": 768
      },
      {
        "bytes": 102634,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-25-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-26.jpeg": {
    "bytes": 153387,
    "height": 1086,
    "quality": 51,
    "webp": [
      {
        "bytes": 28744,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-480.webp",
        "width": 480
      },
      {
        "bytes": 59990,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-768.webp",
        "width": 768
      },
      {
        "bytes": 100212,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-1086.webp",
        "width": 1086
      },
      {
        "bytes": 150300,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-26-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-27.jpeg": {
    "bytes": 153343,
    "height": 1024,
    "quality": 38,
    "webp": [
      {
        "bytes": 34860,
        "height": 320,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-480.webp",
        "width": 480
      },
      {
        "bytes": 72840,
        "height": 512,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-768.webp",
        "width": 768
      },
      {
        "bytes": 114674,
        "height": 724,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-27-1086.webp",
        "width": 1086
      },
      {
        "bytes": 150122,
        "height": 965,
        "quality": 60,
        "src": "assets/variants/gallery/gallery-27-1448.webp",
        "width": 1448
      },
      {
        "bytes": 149398,
        "height": 1024,
        "quality": 54,
        "src": "assets/variants/gallery/gallery-27-1536.webp",
        "width": 1536
      }
    ],
    "width": 1536
  },
  "assets/gallery/gallery-28.jpeg": {
    "bytes": 153530,
    "height": 1448,
    "quality": 65,
    "webp": [
      {
        "bytes": 35452,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-480.webp",
        "width": 480
      },
      {
        "bytes": 74168,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-768.webp",
        "width": 768
      },
      {
        "bytes": 121162,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-28-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-29.jpeg": {
    "bytes": 144960,
    "height": 1448,
    "quality": 84,
    "webp": [
      {
        "bytes": 23196,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-480.webp",
        "width": 480
      },
      {
        "bytes": 44134,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-768.webp",
        "width": 768
      },
      {
        "bytes": 70466,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-29-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-30.jpeg": {
    "bytes": 152688,
    "height": 1448,
    "quality": 82,
    "webp": [
      {
        "bytes": 26290,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-480.webp",
        "width": 480
      },
      {
        "bytes": 50354,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-768.webp",
        "width": 768
      },
      {
        "bytes": 79728,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-30-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-31.jpeg": {
    "bytes": 141823,
    "height": 1448,
    "quality": 84,
    "webp": [
      {
        "bytes": 22898,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-480.webp",
        "width": 480
      },
      {
        "bytes": 42500,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-768.webp",
        "width": 768
      },
      {
        "bytes": 66112,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-31-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-32.jpeg": {
    "bytes": 153446,
    "height": 1448,
    "quality": 79,
    "webp": [
      {
        "bytes": 25694,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-480.webp",
        "width": 480
      },
      {
        "bytes": 52084,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-768.webp",
        "width": 768
      },
      {
        "bytes": 86036,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-32-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-33.jpeg": {
    "bytes": 153442,
    "height": 1448,
    "quality": 71,
    "webp": [
      {
        "bytes": 32960,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-480.webp",
        "width": 480
      },
      {
        "bytes": 66706,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-768.webp",
        "width": 768
      },
      {
        "bytes": 107954,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-33-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-34.jpeg": {
    "bytes": 153113,
    "height": 1448,
    "quality": 73,
    "webp": [
      {
        "bytes": 29794,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-480.webp",
        "width": 480
      },
      {
        "bytes": 62148,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-768.webp",
        "width": 768
      },
      {
        "bytes": 101696,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-34-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-35.jpeg": {
    "bytes": 152801,
    "height": 1448,
    "quality": 70,
    "webp": [
      {
        "bytes": 32582,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-480.webp",
        "width": 480
      },
      {
        "bytes": 66228,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-768.webp",
        "width": 768
      },
      {
        "bytes": 108128,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-35-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-36.jpeg": {
    "bytes": 153560,
    "height": 1086,
    "quality": 73,
    "webp": [
      {
        "bytes": 21154,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-480.webp",
        "width": 480
      },
      {
        "bytes": 40788,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-768.webp",
        "width": 768
      },
      {
        "bytes": 65816,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-1086.webp",
        "width": 1086
      },
      {
        "bytes": 94294,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-36-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-37.jpeg": {
    "bytes": 153535,
    "height": 1086,
    "quality": 60,
    "webp": [
      {
        "bytes": 23724,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-480.webp",
        "width": 480
      },
      {
        "bytes": 49778,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-768.webp",
        "width": 768
      },
      {
        "bytes": 86630,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-1086.webp",
        "width": 1086
      },
      {
        "bytes": 130152,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-37-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-38.jpeg": {
    "bytes": 153181,
    "height": 1448,
    "quality": 70,
    "webp": [
      {
        "bytes": 34816,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-480.webp",
        "width": 480
      },
      {
        "bytes": 67870,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-768.webp",
        "width": 768
      },
      {
        "bytes": 110874,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-38-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-39.jpeg": {
    "bytes": 152850,
    "height": 1086,
    "quality": 60,
    "webp": [
      {
        "bytes": 24704,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-480.webp",
        "width": 480
      },
      {
        "bytes": 51974,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-768.webp",
        "width": 768
      },
      {
        "bytes": 89138,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-1086.webp",
        "width": 1086
      },
      {
        "bytes": 129972,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-39-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-40.jpeg": {
    "bytes": 153183,
    "height": 1448,
    "quality": 70,
    "webp": [
      {
        "bytes": 33714,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-480.webp",
        "width": 480
      },
      {
        "bytes": 63940,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-768.webp",
        "width": 768
      },
      {
        "bytes": 102804,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-40-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-41.jpeg": {
    "bytes": 153193,
    "height": 1448,
    "quality": 79,
    "webp": [
      {
        "bytes": 28072,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-480.webp",
        "width": 480
      },
      {
        "bytes": 54256,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-768.webp",
        "width": 768
      },
      {
        "bytes": 86306,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-41-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-42.jpeg": {
    "bytes": 153158,
    "height": 1448,
    "quality": 72,
    "webp": [
      {
        "bytes": 32458,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-480.webp",
        "width": 480
      },
      {
        "bytes": 63654,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-768.webp",
        "width": 768
      },
      {
        "bytes": 101502,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-42-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-43.jpeg": {
    "bytes": 153393,
    "height": 1448,
    "quality": 60,
    "webp": [
      {
        "bytes": 36048,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-480.webp",
        "width": 480
      },
      {
        "bytes": 79750,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-768.webp",
        "width": 768
      },
      {
        "bytes": 135384,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-43-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-44.jpeg": {
    "bytes": 153513,
    "height": 1086,
    "quality": 56,
    "webp": [
      {
        "bytes": 26318,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-480.webp",
        "width": 480
      },
      {
        "bytes": 54254,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-768.webp",
        "width": 768
      },
      {
        "bytes": 91584,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-1086.webp",
        "width": 1086
      },
      {
        "bytes": 132730,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-44-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-45.jpeg": {
    "bytes": 152359,
    "height": 1448,
    "quality": 75,
    "webp": [
      {
        "bytes": 29462,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-480.webp",
        "width": 480
      },
      {
        "bytes": 57000,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-768.webp",
        "width": 768
      },
      {
        "bytes": 90372,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-45-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-46.jpeg": {
    "bytes": 152946,
    "height": 1448,
    "quality": 70,
    "webp": [
      {
        "bytes": 32304,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-480.webp",
        "width": 480
      },
      {
        "bytes": 67396,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-768.webp",
        "width": 768
      },
      {
        "bytes": 112126,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-46-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-47.jpeg": {
    "bytes": 153522,
    "height": 1448,
    "quality": 65,
    "webp": [
      {
        "bytes": 34792,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-480.webp",
        "width": 480
      },
      {
        "bytes": 71538,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-768.webp",
        "width": 768
      },
      {
        "bytes": 117504,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-47-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-48.jpeg": {
    "bytes": 153270,
    "height": 1448,
    "quality": 81,
    "webp": [
      {
        "bytes": 24880,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-480.webp",
        "width": 480
      },
      {
        "bytes": 48918,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-768.webp",
        "width": 768
      },
      {
        "bytes": 79372,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-48-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-49.jpeg": {
    "bytes": 153527,
    "height": 1448,
    "quality": 70,
    "webp": [
      {
        "bytes": 33008,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-480.webp",
        "width": 480
      },
      {
        "bytes": 65896,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-768.webp",
        "width": 768
      },
      {
        "bytes": 109798,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-49-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-50.jpeg": {
    "bytes": 152669,
    "height": 1448,
    "quality": 72,
    "webp": [
      {
        "bytes": 29864,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-480.webp",
        "width": 480
      },
      {
        "bytes": 63776,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-768.webp",
        "width": 768
      },
      {
        "bytes": 105736,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-50-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/gallery/gallery-51.jpeg": {
    "bytes": 153534,
    "height": 1086,
    "quality": 71,
    "webp": [
      {
        "bytes": 20656,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-480.webp",
        "width": 480
      },
      {
        "bytes": 44356,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-768.webp",
        "width": 768
      },
      {
        "bytes": 75636,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-1086.webp",
        "width": 1086
      },
      {
        "bytes": 108348,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-51-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-52.jpeg": {
    "bytes": 153085,
    "height": 1086,
    "quality": 73,
    "webp": [
      {
        "bytes": 20022,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-480.webp",
        "width": 480
      },
      {
        "bytes": 39404,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-768.webp",
        "width": 768
      },
      {
        "bytes": 64802,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-1086.webp",
        "width": 1086
      },
      {
        "bytes": 98400,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-52-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/gallery/gallery-53.jpeg": {
    "bytes": 153579,
    "height": 1448,
    "quality": 61,
    "webp": [
      {
        "bytes": 38248,
        "height": 640,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-480.webp",
        "width": 480
      },
      {
        "bytes": 74632,
        "height": 1024,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-768.webp",
        "width": 768
      },
      {
        "bytes": 115586,
        "height": 1448,
        "quality": 72,
        "src": "assets/variants/gallery/gallery-53-1086.webp",
        "width": 1086
      }
    ],
    "width": 1086
  },
  "assets/menu/menu-1.jpeg": {
    "bytes": 153339,
    "height": 1103,
    "quality": 21,
    "webp": [
      {
        "bytes": 76044,
        "height": 495,
        "quality": 72,
        "src": "assets/variants/menu/menu-1-640.webp",
        "width": 640
      },
      {
        "bytes": 145772,
        "height": 743,
        "quality": 66,
        "src": "assets/variants/menu/menu-1-960.webp",
        "width": 960
      }
    ],
    "width": 1426
  },
  "assets/menu/menu-2.jpeg": {
    "bytes": 153346,
    "height": 1103,
    "quality": 25,
    "webp": [
      {
        "bytes": 73606,
        "height": 495,
        "quality": 72,
        "src": "assets/variants/menu/menu-2-640.webp",
        "width": 640
      },
      {
        "bytes": 144892,
        "height": 743,
        "quality": 72,
        "src": "assets/variants/menu/menu-2-960.webp",
        "width": 960
      }
    ],
    "width": 1426
  },
  "assets/restaurant/marjorie-gaboyau.jpeg": {
    "bytes": 110302,
    "height": 1537,
    "quality": 84,
    "webp": [
      {
        "bytes": 16282,
        "height": 721,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-480.webp",
        "width": 480
      },
      {
        "bytes": 29830,
        "height": 1154,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-768.webp",
        "width": 768
      },
      {
        "bytes": 44960,
        "height": 1537,
        "quality": 72,
        "src": "assets/variants/restaurant/marjorie-gaboyau-1023.webp",
        "width": 1023
      }
    ],
    "width": 1023
  },
  "assets/restaurant/oswald-gaboyau.jpeg": {
    "bytes": 117047,
    "height": 1537,
    "quality": 84,
    "webp": [
      {
        "bytes": 16696,
        "height": 721,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-480.webp",
        "width": 480
      },
      {
        "bytes": 32686,
        "height": 1154,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-768.webp",
        "width": 768
      },
      {
        "bytes": 52176,
        "height": 1537,
        "quality": 72,
        "src": "assets/variants/restaurant/oswald-gaboyau-1023.webp",
        "width": 1023
      }
    ],
    "width": 1023
  },
  "assets/restaurant/seven-wonders-dining-room-art.jpeg": {
    "bytes": 153305,
    "height": 1086,
    "quality": 54,
    "webp": [
      {
        "bytes": 24788,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-480.webp",
        "width": 480
      },
      {
        "bytes": 52874,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-768.webp",
        "width": 768
      },
      {
        "bytes": 91432,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-1086.webp",
        "width": 1086
      },
      {
        "bytes": 133722,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-art-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/restaurant/seven-wonders-dining-room-front.jpeg": {
    "bytes": 153533,
    "height": 1086,
    "quality": 51,
    "webp": [
      {
        "bytes": 29388,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-480.webp",
        "width": 480
      },
      {
        "bytes": 58908,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-768.webp",
        "width": 768
      },
      {
        "bytes": 97380,
        "height": 814,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-1086.webp",
        "width": 1086
      },
      {
        "bytes": 139706,
        "height": 1086,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-dining-room-front-1448.webp",
        "width": 1448
      }
    ],
    "width": 1448
  },
  "assets/restaurant/seven-wonders-exterior.jpeg": {
    "bytes": 153393,
    "height": 960,
    "quality": 37,
    "webp": [
      {
        "bytes": 42158,
        "height": 360,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-exterior-480.webp",
        "width": 480
      },
      {
        "bytes": 89740,
        "height": 576,
        "quality": 72,
        "src": "assets/variants/restaurant/seven-wonders-exterior-768.webp",
        "width": 768
      },
      {
        "bytes": 145918,
        "height": 814,
        "quality": 66,
        "src": "assets/variants/restaurant/seven-wonders-exterior-1086.webp",
        "width": 1086
      },
      {
        "bytes": 149070,
        "height": 960,
        "quality": 48,
        "src": "assets/variants/restaurant/seven-wonders-exterior-1280.webp",
        "width": 1280
      }
    ],
    "width": 1280
  }
};

  function esc(value) {
    return String(value == null ? "" : value)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/\"/g, "&quot;").replace(/'/g, "&#39;");
  }
  function meta(src) { return META[String(src || "").trim()] || null; }
  function attrs(src, opts) {
    opts = opts || {};
    var m = meta(src) || {};
    var out = { src: src, width: m.width || opts.width || 1, height: m.height || opts.height || 1,
      loading: opts.loading || "lazy", decoding: opts.decoding || "async" };
    var srcset = webpSrcset(src);
    if (srcset) { out.srcset = srcset; out.sizes = opts.sizes || "100vw"; }
    if (opts.fetchpriority) out.fetchpriority = opts.fetchpriority;
    return out;
  }
  function webpSrcset(src) {
    var m = meta(src);
    return m && m.webp && m.webp.length ? m.webp.map(function (v) { return v.src + " " + v.width + "w"; }).join(", ") : "";
  }
  function makeSource(src, sizes) {
    var srcset = webpSrcset(src);
    if (!srcset) return null;
    var s = document.createElement("source");
    s.type = "image/webp";
    s.srcset = srcset;
    s.sizes = sizes || "100vw";
    return s;
  }
  function applyToImage(img, src, alt, opts) {
    var a = attrs(src, opts);
    Object.keys(a).forEach(function (k) { img.setAttribute(k, a[k]); });
    img.alt = alt || "";
    var parent = img.parentNode;
    if (parent && parent.tagName === "PICTURE") {
      var source = parent.querySelector('source[type="image/webp"]');
      var fresh = makeSource(src, (opts || {}).sizes);
      if (fresh && source) { source.srcset = fresh.srcset; source.sizes = fresh.sizes; }
      else if (fresh) parent.insertBefore(fresh, img);
      else if (source) source.remove();
    }
  }
  function picture(src, alt, opts) {
    opts = opts || {};
    var p = document.createElement("picture");
    if (opts.className) p.className = opts.className;
    var source = makeSource(src, opts.sizes);
    if (source) p.appendChild(source);
    var img = document.createElement("img");
    if (opts.imgClass) img.className = opts.imgClass;
    applyToImage(img, src, alt, opts);
    p.appendChild(img);
    return p;
  }
  function html(src, alt, opts) {
    opts = opts || {};
    var m = meta(src) || {};
    var cls = opts.imgClass ? ' class="' + esc(opts.imgClass) + '"' : "";
    var source = webpSrcset(src)
      ? '<source type="image/webp" srcset="' + esc(webpSrcset(src)) + '" sizes="' + esc(opts.sizes || "100vw") + '">'
      : "";
    var fetch = opts.fetchpriority ? ' fetchpriority="' + esc(opts.fetchpriority) + '"' : "";
    return '<picture>' + source + '<img' + cls + ' src="' + esc(src) + '" alt="' + esc(alt || "") + '" width="' +
      esc(m.width || opts.width || 1) + '" height="' + esc(m.height || opts.height || 1) + '" loading="' +
      esc(opts.loading || "lazy") + '" decoding="async"' + fetch + '></picture>';
  }

  window.SW_IMAGE_META = META;
  window.SWImage = { meta: meta, attrs: attrs, picture: picture, html: html, applyToImage: applyToImage, webpSrcset: webpSrcset };
})();
