from pathlib import Path
from PIL import Image, ImageOps
import json

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
VARIANTS = ASSETS / "variants"
MANIFEST = ROOT / "js" / "image-meta.js"
MAX_BYTES = 153_600
JPEG_QUALITY_MIN = 18
JPEG_QUALITY_MAX = 84
WEBP_QUALITY_MIN = 24
WEBP_QUALITY_START = 72
WIDTHS = (240, 360, 480, 768, 1086, 1448)
MENU_WIDTHS = (480, 640, 960)


def rel(path):
    return path.relative_to(ROOT).as_posix()


def load_image(path):
    with Image.open(path) as image:
        image = ImageOps.exif_transpose(image)
        if image.mode not in ("RGB", "L"):
            image = image.convert("RGB")
        elif image.mode == "L":
            image = image.convert("RGB")
        return image.copy()


def save_jpeg_under_limit(image, path):
    chosen = None
    low, high = JPEG_QUALITY_MIN, JPEG_QUALITY_MAX
    while low <= high:
        quality = (low + high) // 2
        image.save(path, "JPEG", quality=quality, optimize=True, progressive=True)
        size = path.stat().st_size
        if size <= MAX_BYTES:
            chosen = quality
            low = quality + 1
        else:
            high = quality - 1
    if chosen is None:
        chosen = JPEG_QUALITY_MIN
    image.save(path, "JPEG", quality=chosen, optimize=True, progressive=True)
    return path.stat().st_size, chosen


def save_webp_under_limit(image, path):
    chosen = WEBP_QUALITY_START
    for quality in range(WEBP_QUALITY_START, WEBP_QUALITY_MIN - 1, -6):
        image.save(path, "WEBP", quality=quality, method=4)
        chosen = quality
        if path.stat().st_size <= MAX_BYTES:
            break
    return path.stat().st_size, chosen


def resized(image, target_width):
    if target_width >= image.width:
        return image.copy()
    height = round(image.height * (target_width / image.width))
    return image.resize((target_width, height), Image.Resampling.LANCZOS)


def webp_widths_for(path, image):
    is_menu_scan = "/menu/" in rel(path)
    widths = MENU_WIDTHS if is_menu_scan else WIDTHS
    out = []
    for width in widths:
        if width <= image.width and width not in out:
            out.append(width)
    if not is_menu_scan and image.width not in out:
        out.append(image.width)
    return out


def main():
    manifest = {}
    originals = []
    expected_variants = set()
    for path in sorted(ASSETS.rglob("*")):
        if "variants" in path.parts:
            continue
        if path.suffix.lower() not in (".jpg", ".jpeg"):
            continue
        originals.append(path)

    for path in originals:
        image = load_image(path)
        original_width, original_height = image.size
        current_size = path.stat().st_size
        if current_size <= MAX_BYTES:
            jpeg_size, jpeg_quality = current_size, None
        else:
            jpeg_size, jpeg_quality = save_jpeg_under_limit(image, path)

        variants = []
        out_dir = VARIANTS / path.relative_to(ASSETS).parent
        out_dir.mkdir(parents=True, exist_ok=True)
        for width in webp_widths_for(path, image):
            variant = resized(image, width)
            out = out_dir / f"{path.stem}-{width}.webp"
            webp_size, webp_quality = save_webp_under_limit(variant, out)
            expected_variants.add(out)
            variants.append({
                "src": rel(out),
                "width": variant.width,
                "height": variant.height,
                "bytes": webp_size,
                "quality": webp_quality,
            })

        manifest[rel(path)] = {
            "width": original_width,
            "height": original_height,
            "bytes": jpeg_size,
            "quality": jpeg_quality,
            "webp": variants,
        }

    removed = 0
    for path in sorted(VARIANTS.rglob("*.webp")):
        if path not in expected_variants:
            path.unlink()
            removed += 1

    MANIFEST.write_text(
        "/* Generated by scripts/optimize-images.py. Do not hand-edit. */\n"
        "(function () {\n"
        "  \"use strict\";\n\n"
        "  var META = " + json.dumps(manifest, indent=2, sort_keys=True) + ";\n\n"
        "  function esc(value) {\n"
        "    return String(value == null ? \"\" : value)\n"
        "      .replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\")\n"
        "      .replace(/\\\"/g, \"&quot;\").replace(/'/g, \"&#39;\");\n"
        "  }\n"
        "  function meta(src) { return META[String(src || \"\").trim()] || null; }\n"
        "  function attrs(src, opts) {\n"
        "    opts = opts || {};\n"
        "    var m = meta(src) || {};\n"
        "    var out = { src: src, width: m.width || opts.width || 1, height: m.height || opts.height || 1,\n"
        "      loading: opts.loading || \"lazy\", decoding: opts.decoding || \"async\" };\n"
        "    var srcset = webpSrcset(src);\n"
        "    if (srcset) { out.srcset = srcset; out.sizes = opts.sizes || \"100vw\"; }\n"
        "    if (opts.fetchpriority) out.fetchpriority = opts.fetchpriority;\n"
        "    return out;\n"
        "  }\n"
        "  function webpSrcset(src) {\n"
        "    var m = meta(src);\n"
        "    return m && m.webp && m.webp.length ? m.webp.map(function (v) { return v.src + \" \" + v.width + \"w\"; }).join(\", \") : \"\";\n"
        "  }\n"
        "  function makeSource(src, sizes) {\n"
        "    var srcset = webpSrcset(src);\n"
        "    if (!srcset) return null;\n"
        "    var s = document.createElement(\"source\");\n"
        "    s.type = \"image/webp\";\n"
        "    s.srcset = srcset;\n"
        "    s.sizes = sizes || \"100vw\";\n"
        "    return s;\n"
        "  }\n"
        "  function applyToImage(img, src, alt, opts) {\n"
        "    var a = attrs(src, opts);\n"
        "    Object.keys(a).forEach(function (k) { img.setAttribute(k, a[k]); });\n"
        "    img.alt = alt || \"\";\n"
        "    var parent = img.parentNode;\n"
        "    if (parent && parent.tagName === \"PICTURE\") {\n"
        "      var source = parent.querySelector('source[type=\"image/webp\"]');\n"
        "      var fresh = makeSource(src, (opts || {}).sizes);\n"
        "      if (fresh && source) { source.srcset = fresh.srcset; source.sizes = fresh.sizes; }\n"
        "      else if (fresh) parent.insertBefore(fresh, img);\n"
        "      else if (source) source.remove();\n"
        "    }\n"
        "  }\n"
        "  function picture(src, alt, opts) {\n"
        "    opts = opts || {};\n"
        "    var p = document.createElement(\"picture\");\n"
        "    if (opts.className) p.className = opts.className;\n"
        "    var source = makeSource(src, opts.sizes);\n"
        "    if (source) p.appendChild(source);\n"
        "    var img = document.createElement(\"img\");\n"
        "    if (opts.imgClass) img.className = opts.imgClass;\n"
        "    applyToImage(img, src, alt, opts);\n"
        "    p.appendChild(img);\n"
        "    return p;\n"
        "  }\n"
        "  function html(src, alt, opts) {\n"
        "    opts = opts || {};\n"
        "    var m = meta(src) || {};\n"
        "    var cls = opts.imgClass ? ' class=\"' + esc(opts.imgClass) + '\"' : \"\";\n"
        "    var source = webpSrcset(src)\n"
        "      ? '<source type=\"image/webp\" srcset=\"' + esc(webpSrcset(src)) + '\" sizes=\"' + esc(opts.sizes || \"100vw\") + '\">'\n"
        "      : \"\";\n"
        "    var fetch = opts.fetchpriority ? ' fetchpriority=\"' + esc(opts.fetchpriority) + '\"' : \"\";\n"
        "    return '<picture>' + source + '<img' + cls + ' src=\"' + esc(src) + '\" alt=\"' + esc(alt || \"\") + '\" width=\"' +\n"
        "      esc(m.width || opts.width || 1) + '\" height=\"' + esc(m.height || opts.height || 1) + '\" loading=\"' +\n"
        "      esc(opts.loading || \"lazy\") + '\" decoding=\"async\"' + fetch + '></picture>';\n"
        "  }\n\n"
        "  window.SW_IMAGE_META = META;\n"
        "  window.SWImage = { meta: meta, attrs: attrs, picture: picture, html: html, applyToImage: applyToImage, webpSrcset: webpSrcset };\n"
        "})();\n",
        encoding="utf-8",
    )

    print(f"Optimized {len(originals)} images")
    if removed:
        print(f"Removed {removed} stale WebP variants")
    print(f"Manifest: {rel(MANIFEST)}")


if __name__ == "__main__":
    main()
